name: "Biochemical Network - Read"
description: "Benchmark simple biochemical network with: Increasing C_in, Increasing R_out, and Constant A_out"
dataGenerator: "biochemical_network"
schema: "biochemical_network.gql"
scales:
  - 2000
  - 4000
  - 6000 # large number of role players => slow at large scales
repeatsPerQuery: 10

queries: "queries_read.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: false

concurrency:
  clients: 1
  uniqueKeyspaces: true