name: "Attributes - Data operations"
description: "Benchmark Grakn's performance when operating on only data, no entities or relations (beyond keys) included"
dataGenerator: "attribute"
schema: "attribute_schema.gql"
scales:
  - 1000
  - 3000
  - 5000
repeatsPerQuery: 10

queries: "queries_read.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: false

concurrency:
  clients: 1
  uniqueKeyspaces: true